### ISSUE TITLE
Plot Total ion chromatograms

### ISSUE THREAD

**Issue by QizhiSu** [acinostroza/TargetSearch#2]
Dear Developers,

I am wondering if it is possible to plot TIC with the TargetSearch package?

Thanks a lot, in advance. 

Best regards, 
Qizhi Su

**Comment by acinostroza** [comment]
First of all, I assume you have a(some) chromatogram file(s) in NetCDF format. If no, then jump to the last paragraph. If yes, then the answer to your question is YES and NO.

**NO,** because `TargetSearch` does not have a built-in function to plot the total ion count (TIC). I may consider add such feature in the future though.

**YES,** because you can extract the TIC data and plot them yourself using R's plot function. For example (assuming "sample.cdf" is the file to plot).

```R
  library(TargetSearch)
  data <- peakCDFextraction('sample.cdf')
  time <- data$Time
  tic <- rowSums(data$Peaks)
  plot(time, tic, type='l')
```

Alternatively, you can use the package `ncdf4` from CRAN directly (this is the simplest option in my opinion)

```R
  library(ncdf4)
  nc <- nc_open('sample.cdf')
  time <- ncvar_get(nc, 'scan_acquisition_time')
  tic <- ncvar_get(nc, 'total_intensity')
  nc_close(nc)
  plot(time, tic, type='l')
```

Finally, you can try with the package `xmcs` from bioconductor. It has a function called `plotTIC` exactly for this.

If your chromatogram files are in another format (not NetCDF), such as mzML, then the answer is definitely NO. In this case, use the package `xcms` as I mentioned above.

**Comment by QizhiSu** [comment]
Huge thanks for your quick and detailed answer @acinostroza ！！

1. Yes, I have netCDF files to be plotted. I did tried xcmsRaw() from XCMS and readMSData() from MSnbase, but both of them failed to read my netCDF files. 
`cdfpath <- system.file("cdf", package = "faahKO")
cdffiles <- list.files(cdfpath, recursive = TRUE, full.names = TRUE)
xr<-xcmsRaw(cdffiles[1])`

    Error in validObject(.Object) : 
  invalid class “xcmsFileSource” object: superclass "characterORconnection" not defined in the environment of the object's class

   `xr <- readMSData(cdffiles[1])`

    Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.
Error in readInMemMSData(files, pdata = pdata, msLevel. = msLevel., verbose = verbose,  : 
  No MS(n>1) spectra in fileC:\Users\qizhi\Documents\R\win-library\4.0\faahKO\cdf\KO\ko15.CDF

2. I did noticed that peakCDFextraction() return the retention time - ion abundance matrix, but I didn't realize that the TIC is simply the sum of all ions... I think ncdf4 is an good option as well. Thank you very much a gain. 

Best regards, 
Qizhi Su
